from typing import overload

from hocon.constants import ANY_VALUE_TYPE, ROOT_TYPE, SIMPLE_VALUE_TYPE, Undefined
from hocon.unresolved import UnresolvedSubstitution

def resolve(parsed: ROOT_TYPE) -> ROOT_TYPE: ...

class Resolver:
    def __init__(self, parsed: ROOT_TYPE) -> None: ...
    @overload
    def resolve(self, values: dict) -> dict: ...
    @overload
    def resolve(self, values: list) -> list: ...
    @overload
    def resolve(self, values: SIMPLE_VALUE_TYPE) -> SIMPLE_VALUE_TYPE: ...
    @overload
    def resolve(self, values: UnresolvedSubstitution) -> ANY_VALUE_TYPE | Undefined: ...
