name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install hatch coverage
      - name: Black
        run: hatch run test:black
      - name: MyPy
        run: hatch run test:mypy
      - name: Pytest
        run: export PYTHON_VERSION=${{ matrix.python-version }} && hatch run test:coverage
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results.xml-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: myjniak/hocon